const express = require('express');
const router = express.Router();
const notesController = require("../controllers/notesController");
const authMiddleware = require("../middleware/authMIddleware");
router.post('/createnote', authMiddleware, notesController.createNote);
router.put('/updatenote/:id', authMiddleware, notesController.updateNote);
router.delete('/deletenote/:id', authMiddleware, notesController.deleteNote);
router.get('/getnotes',authMiddleware, notesController.getAllNotes );
router.get('/getnotebyid/:id',authMiddleware,  notesController.getNoteById);
module.exports = router;